config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'

  resources :sessions
  resources :users do
    resources :profiles
  end
  resources :posts
  resources :comments
  delete '/logout' => 'sessions#destroy'

end

app/models/profile.rb
#for retrieving the image from the remote url
require 'open-uri' 

class Profile < ActiveRecord::Base

  #validates_presence_of :email

  belongs_to :user
  
  has_attached_file :photo,
                    :styles => {:sprite => "20x20#", :thumb => "70x70#", :small => "100x100>"},
                    :url => "/assets/:id/:style/:basename.:extension",
                    :default_url => ":style/dumbbell.jpg",
                    :path => ":rails_root/public/assets/:id/:style/:basename.:extension"

  validates_attachment_size :photo, :less_than => 5.megabytes
  validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']

  #pull the image from the remote url and assign it as the avatar
  #def photo_from_url(url)
    #self.photo = open(url)
  #end

  #before_validation :download_remote_image, :if => :photo_url_provided?
 
  #validates_presence_of :photo_remote_url, :if => :photo_url_provided?, :message => 'is invalid or inaccessible'
    
  private
  
  def photo_url_provided?
    #!self.photo_url.blank?
    photo_url.blank?
  end
  
  def download_remote_photo
    io = open(URI.parse(photo_url))
    self.original_filename = io.base_uri.path.split('/').last
    self.photo = io
    self.photo_remote_url = photo_url
  #rescue # catch url errors with validations instead of exceptions (Errno::ENOENT, OpenURI::HTTPError, etc...)
  end
  
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  
  # create route is not yet defined - it is actually being done in users controller in user create method

  def index
    @profiles = Profile.all
  end

  def new
    @profile = Profile.new
  end

  def show
    @profile = Profile.find params[:id]
  end

  def edit
    @profile = Profile.find(params[:id])
  end

  def update
    @profile = Profile.where("user_id = #{params[:id]}").first

    #pull the image from the specified url and set the user's avatar
    fname = params[:profile][:firstname]
    lname = params[:profile][:lastname]
    email = params[:profile][:email]
    pic = params[:photo_url]
    new_profile_hash = {:firstname => fname, :lastname => lname, :email => email, :photo => pic}
    #@profile.update new_profile_hash 
    @profile.update profile_params
    if @profile.valid?
      @response_type = 'SUCCESS'
      @response = 'Profile updated.'
    else
      @response_type = 'ERROR'
      @response = 'There was an error with your submission'
    end
    redirect_to edit_user_profile_path
  end

  def destroy
    @profile = Profile.find(params[:id])
    :profile.activated = false
    @profile.update params[:profile]
    redirect_to edit_user_profile_path
  end

  def profile_params
    params.require(:profile).permit(:id,
                                    :user_id,
                                    :firstname,
                                    :lastname,
                                    :email,
                                    :photo
                                   )
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_profile.html.erb
<%= form_for([@user, @profile], :url => edit_user_profile_path(@profile.id, @profile.user_id), :html => { :multipart => true }) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :firstname %>
  <%= f.text_field :firstname, { placeholder: "First Name"} %> <br>
  <%= f.label :lastname %>
  <%= f.text_field :lastname, { placeholder: "Last Name"} %> <br>
  <%= f.label :email %>
  <%= f.text_field :email, { placeholder: "Email"} %> <br>
  <%= f.file_field :photo %> <br>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<div class="lhs">
  <p> Current Profile Picture </p>
  <%= image_tag @profile.photo.url(:thumb) %>
</div>

<div class="rhs">
  <%= form_for([@user, @profile], :url => user_profile_path(@profile.id, @profile.user_id), :html => { :multipart => true, :method => "patch" }) do |f| %>
    <% if @profile.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

        <ul>
        <% @profile.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <h1> Edit User Profile </h1>

    <% f.fields_for :user do |u| %>  
      <%= u.label :username %>
      <%= u.text_field :username, { placeholder: "Username"} %> <br>
    <% end %> 

    <% if :activated %> <br>
      <span>Account is enabled  </span>
      <span id="button5" class="custom_button"><%= link_to 'Disable Account', user_profile_path(@profile.id, @profile.user_id) %></span> 
    <% else %> 
      <span id="button6" class="custom_button"><%= link_to 'Enable Account', user_profile_path(@profile.id, @profile.user_id) %></span> 
    <% end %> 

    <%= f.label :firstname %>
    <%= f.text_field :firstname, { placeholder: "First Name"} %> <br>
    <%= f.label :lastname %>
    <%= f.text_field :lastname, { placeholder: "Last Name"} %> <br>
    <%= f.label :email %>
    <%= f.text_field :email, { placeholder: "Email"} %> <br>
    <%= f.label :created_at %>
    <%= f.date_field :created_at, :readonly => true %> 
    <%= f.label :updated_at %>
    <%= f.date_field :updated_at, :readonly => true %> <br><br>
  
    <span id="button_fileupload"><%= f.file_field :photo %></span>
    <span id="from_url">Provide a URL for Your Avatar: <%= text_field_tag 'photo_url' %></span>
    <div class="actions">
      <span id="button4" class="custom_button"><%= f.submit :Update %></span>
    </div>
  <% end %>
  <br>
  <span id="button6" class="custom_button"><%= link_to 'Back', posts_path %></span>
</div>

app/views/profiles/index.html.erb
<h1>Listing Profiles</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= link_to 'Show', user_profiles_path %></td>
        <td><%= link_to 'Show', user_profiles_path %></td>
        <td><%= link_to 'Edit', edit_user_profile_path(profile.id, profile.user_id) %></td> 
        <td><%= link_to 'Destroy', user_profile_path(profile.id, profile.user_id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'New Profile', new_user_profile_path %>

app/views/profiles/show.html.erb
<div class="lhs">
  <p> Current Profile Picture </p>
  <%= image_tag @profile.photo.url(:thumb) %>
  <%= image_tag @profile.photo.url %>
</div>

<div class="rhs">
  <%= form_for([@user, @profile], :url => user_profile_path(@profile.id, @profile.user_id), :html => { :multipart => true, :method => "patch" }) do |f| %>
    <% if @profile.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

        <ul>
        <% @profile.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <h1> Edit User Profile </h1>

    <% f.fields_for :user do |u| %>  
      <%= u.label :username %>
      <%= u.text_field :username, { placeholder: "Username"} %> <br>
    <% end %> 

    <% if :activated %> <br>
      <span>Account is enabled  </span>
      <span id="button5" class="custom_button"><%= link_to 'Disable Account', edit_user_profile_path(@profile.id, @profile.user_id) %></span> 
    <% else %> 
      <span id="button6" class="custom_button"><%= link_to 'Enable Account', edit_user_profile_path(@profile.id, @profile.user_id) %></span> 
    <% end %> 

    <%= f.label :firstname %>
    <%= f.text_field :firstname, { placeholder: "First Name"} %> <br>
    <%= f.label :lastname %>
    <%= f.text_field :lastname, { placeholder: "Last Name"} %> <br>
    <%= f.label :email %>
    <%= f.text_field :email, { placeholder: "Email"} %> <br>
    <%= f.label :created_at %>
    <%= f.date_field :created_at, :readonly => true %> 
    <%= f.label :updated_at %>
    <%= f.date_field :updated_at, :readonly => true %> <br><br>
  
    <span id="button_fileupload"><%= f.file_field :photo %></span>
    <div class="actions">
      <span id="button4" class="custom_button"><%= f.submit :Update %></span>
    </div>
  <% end %>
  <br>
  <span id="button6" class="custom_button"><%= link_to 'Back', posts_path %></span>
</div>