config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'

  resources :sessions
  resources :users do
    resources :profiles
  end
  resources :posts
  resources :comments
  delete '/logout' => 'sessions#destroy'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :user
    belongs_to :post
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
    @comments = Comment.all.reverse
  end

  def show
    puts "@post.inspect is :  #{@comment.inspect}"
    puts "params.inspect is :  #{params.inspect}"
    @comment = Comment.find params[:id]
  end

  def new
    @comment = Post.find(@post.id).comment.new
    flash[:notice] = "Saved Comment"
  end

  def create
    if current_user
      @comment = current_user.comments.create params[:comment]
      flash[:notice] = "Saved Comment"
      redirect_to post_path(@comment.post)
    else
      flash[:alert] = "Please login to add comment"
      redirect_to post_path(params[:comment][:post_id])
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    flash[:notice] = "Removed Comment"
    @comment.destroy
    redirect_to comments_path
  end

  def edit
    @comment = Comment.find(params[:id])
    flash[:notice] = "Updated Comment"
  end

  def update
    @comment = Comment.find(params[:id])
    @comment.update params[:comment]
    flash[:notice] = "Updated Comment"
    redirect_to edit_comment_path
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/create.html.erb
<%= form_for @comment do |f| %>
  <%= f.label :body %>
  <%= f.text_field :body, { placeholder: "Body"} %> <br>
  <%= f.submit :create %>
<% end %>

app/views/comments/edit.html.erb
<%= form_for @comment do |f| %>
  <h1>Edit comment</h1>
  <%= f.label :body %>
  <%= f.text_field :body, { placeholder: "Body"} %> <br>
  <%= f.submit :edit %>
<% end %>

app/views/comments/index.html.erb
<h2>List of all comments</h2>
 <% @comments.each do |comment| %>
   <%= link_to comment.body, comment_path(comment.id) %> <br>
 <% end %>

app/views/comments/new.html.erb
<%= form_for @comment do |f| %>
  <h1>New comment</h1>
  <%= f.label :body %>
  <%= f.text_field :body, { placeholder: "Body"} %> <br>
  <%= f.submit :create %>
<% end %>

app/views/comments/show.html.erb
<%= form_tag(@comment) do  %>
  <h1>View comment</h1>
  <%= label_tag :body %>
  <%= text_area_tag :body, value=@comment.body %> <br>

  <%= link_to "Delete Comment", comment_path(@comment.id), method: :delete %> <br>
  <%= link_to "Edit Comment", edit_comment_path(@comment.id) %> <br>
<% end %>