config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'

  resources :sessions
  resources :users do
    resources :profiles
  end
  resources :posts
  resources :comments
  delete '/logout' => 'sessions#destroy'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include ApplicationHelper

end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_user
    if session[:user_id]
      @current_user ||= User.find session[:user_id]
    end
  end

end

app/views/application/_header.html.erb
<header>
   <div id="outerNav">
     <div id="icon">
     </div>
     <div id="user_options">
       <% if !current_user %>
         <span id="doLogin"> 
           <%= form_tag('/sessions', :html => {:id => 'form-signin', :class => 'form-signin'}) do %>
             <span><%= text_field_tag :username, nil, placeholder: "Username" %></span> 
             <span><%= password_field_tag :password, nil, placeholder: "Password" %></span>
             <%= submit_tag "Log In" %>
           <% end %>
         </span>
         <span id="signup">
           <%= link_to "Sign Up", new_user_path, method: :get %>
         </span>
       <% else %>
          <div id="sprite">
            <span><%= image_tag current_user.profile.photo.url(:sprite) %></span>
          </div>
          <div id="menu_options">
            <span id="menu_option_1">
              <%= link_to current_user.username, posts_path %>    
            </span>
            <span id="menu_option_2">
              <%= link_to "Create new post", new_post_path %>   
            </span>
            <span id="menu_option_3">
              <%= link_to "Manage Account", edit_user_profile_path(current_user.id, current_user.profile.id) %>    
            </span>
            <span id="menu_option_4">
              <%= link_to "Home", posts_path %>   
            </span>
          </div>
          <span id="doLogout">
            <%= link_to "Sign Out", '/logout', method: :delete %>
          </span>
       <% end %> 
     </div>
  
  
   <% if flash[:notice] %>
     <div id="flash_msg">
       <%= flash[:notice] %>
     </div>
   <% end %>
   <% if flash[:alert] %>
     <div id="flash_msg">
       <%= flash[:alert] %>
     </div>
   <% end %>
   </div>
</header>